name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run unit tests
        run: go test ./... -cover



  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Formatting Check
        run: test -z $(go fmt ./...)


  lint:
    name: Linting
    runs-on: ubuntu-latest

    needs: [tests, style]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"    
